# Generated by Django 6.0.3 on 2026-03-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0003_classlist_created_by_classlist_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='delist',
            field=models.BooleanField(default=False),
        ),
    ]
