# Generated by Django 6.0.3 on 2026-03-20 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_account', '0006_companies_school_category'),
        ('school_management', '0004_classlist_delist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company_school_class', to='company_account.companies'),
        ),
        migrations.CreateModel(
            name='SectionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default=None, max_length=50)),
                ('num_of_stud', models.IntegerField(blank=True, null=True)),
                ('class_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_school_section', to='school_management.classlist')),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company_school_section', to='company_account.companies')),
            ],
        ),
    ]
