# Generated by Django 6.0.3 on 2026-03-20 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0005_alter_classlist_company_sectionlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionlist',
            name='created_by',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sectionlist',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sectionlist',
            name='delist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sectionlist',
            name='updated_by',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sectionlist',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
