# Generated by Django 6.0.3 on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0007_teacherlist"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE school_management_teacherlist
                        ALTER COLUMN dob TYPE timestamp with time zone
                        USING (
                            CASE
                                WHEN dob IS NULL THEN NULL
                                WHEN dob BETWEEN 10000101 AND 99991231
                                    THEN to_timestamp(dob::text, 'YYYYMMDD')
                                WHEN dob > 0
                                    THEN to_timestamp(dob)
                                ELSE NULL
                            END
                        );
                    """,
                    reverse_sql="""
                        ALTER TABLE school_management_teacherlist
                        ALTER COLUMN dob TYPE integer
                        USING (
                            CASE
                                WHEN dob IS NULL THEN NULL
                                ELSE to_char(dob AT TIME ZONE 'UTC', 'YYYYMMDD')::integer
                            END
                        );
                    """,
                )
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="teacherlist",
                    name="dob",
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
    ]
