# Generated by Django 6.0.3 on 2026-03-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0008_alter_teacherlist_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherlist',
            name='is_head_master',
            field=models.BooleanField(default=False),
        ),
    ]
