# Generated by Django 6.0.3 on 2026-03-20 12:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_account', '0007_companies_school_fields'),
        ('school_management', '0009_teacherlist_is_head_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('delist', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='company_account.companies')),
            ],
        ),
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('username', models.CharField(default='', max_length=100, null=True)),
                ('guardian_mobile', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('guardian_email', models.EmailField(default=None, max_length=60)),
                ('dob', models.DateField(blank=True, null=True)),
                ('guardian_name', models.CharField(default='', max_length=100, null=True)),
                ('address', models.CharField(default='', max_length=255, null=True)),
                ('state', models.CharField(default='', max_length=50, null=True)),
                ('city', models.CharField(default='', max_length=50, null=True)),
                ('pin', models.CharField(default='', max_length=50, null=True)),
                ('attachment_id', models.IntegerField(blank=True, null=True)),
                ('delist', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company_school_student', to='company_account.companies')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(blank=True, max_length=30, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('promoted', 'Promoted'), ('detained', 'Detained'), ('passed_out', 'Passed Out'), ('left', 'Left')], default='active', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('delist', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='school_management.academicyear')),
                ('class_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='school_management.classlist')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_academic_records', to='company_account.companies')),
                ('section_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='school_management.sectionlist')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='school_management.studentlist')),
            ],
            options={
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
