# Generated by Django 6.0.3 on 2026-03-24 09:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_account', '0008_companyuser_city_companyuser_dob_and_more'),
        ('school_management', '0010_academicyear_studentlist_studentacademicrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonTeacherStaffList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('username', models.CharField(default='', max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.EmailField(default=None, max_length=60, verbose_name='email')),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('qualification', models.CharField(default='', max_length=100, null=True)),
                ('experience', models.CharField(default='', max_length=100, null=True)),
                ('address', models.CharField(default='', max_length=255, null=True)),
                ('state', models.CharField(default='', max_length=50, null=True)),
                ('city', models.CharField(default='', max_length=50, null=True)),
                ('pin', models.CharField(default='', max_length=50, null=True)),
                ('attachment_id', models.IntegerField(blank=True, null=True)),
                ('delist', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company_school_non_teacher', to='company_account.companies')),
            ],
        ),
    ]
