# Generated by Django 6.0.3 on 2026-03-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0011_nonteacherstafflist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentlist',
            old_name='guardian_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='studentlist',
            old_name='guardian_mobile',
            new_name='mobile',
        ),
    ]
