# Generated by Django 6.0.3 on 2026-03-31 07:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_account', '0009_companyuser_teacher_subject_and_class_lists'),
        ('school_management', '0013_subjectlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('unit_test', 'Unit Test'), ('monthly_test', 'Monthly Test'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('annual', 'Annual'), ('practical', 'Practical'), ('other', 'Other')], default='other', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('delist', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_masters', to='school_management.academicyear')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_masters', to='company_account.companies')),
            ],
        ),
    ]
