# Generated by Django 6.0.3 on 2026-03-31 07:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_account', '0009_companyuser_teacher_subject_and_class_lists'),
        ('school_management', '0014_examtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=33, max_digits=6)),
                ('exam_room', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('instructions', models.TextField(blank=True, default='')),
                ('delist', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='school_management.classlist')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='company_account.companies')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='school_management.examtype')),
                ('section_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='school_management.sectionlist')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='school_management.subjectlist')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exam', 'class_details', 'section_details', 'subject'), name='unique_exam_schedule_per_subject')],
            },
        ),
    ]
