# Generated by Django 6.0.3 on 2026-03-31 13:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_account', '0009_companyuser_teacher_subject_and_class_lists'),
        ('school_management', '0015_examschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_marks', models.JSONField(blank=True, default=dict)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=33, max_digits=6)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('practical_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('internal_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grade', models.CharField(blank=True, default='', max_length=10)),
                ('is_absent', models.BooleanField(default=False)),
                ('is_pass', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('delist', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='school_management.classlist')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='company_account.companies')),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='school_management.examschedule')),
                ('section_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='school_management.sectionlist')),
                ('student_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='school_management.studentacademicrecord')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='school_management.subjectlist')),
            ],
        ),
    ]
