# Generated by Django 6.0.3 on 2026-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0017_studentsmark_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='subject',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
