# Generated by Django 6.0.3 on 2026-04-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_account', '0009_companyuser_teacher_subject_and_class_lists'),
        ('school_management', '0019_alter_examschedule_section_details'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examschedule',
            name='unique_exam_schedule_per_subject',
        ),
        migrations.AddField(
            model_name='examschedule',
            name='subject_schedules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='examschedule',
            constraint=models.UniqueConstraint(fields=('exam', 'class_details', 'section_details'), name='unique_exam_schedule_per_class_section'),
        ),
    ]
