# Generated by Django 6.0.3 on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0020_remove_examschedule_unique_exam_schedule_per_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicyear",
            name="start_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="end_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
