# Generated by Django 6.0.3 on 2026-04-13 10:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_account', '0009_companyuser_teacher_subject_and_class_lists'),
        ('school_management', '0025_alter_total_marks_to_integer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caution_money', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annual_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly'), ('one_time', 'One Time')], default='monthly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('delist', models.BooleanField(default=False)),
                ('delist_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('delist_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_fee_structures', to='school_management.academicyear')),
                ('class_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_fee_structures', to='school_management.classlist')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_fee_structures', to='company_account.companies')),
            ],
            options={
                'unique_together': {('class_details', 'academic_year')},
            },
        ),
    ]
