# Generated by Django 6.0.3 on 2026-04-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0027_rename_classfeestructure_caution_money_exam_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classfeestructure',
            name='frequency',
        ),
    ]
