# Generated by Django 6.0.3 on 2026-04-13 11:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_account', '0009_companyuser_teacher_subject_and_class_lists'),
        ('school_management', '0028_remove_classfeestructure_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeesCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_name', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly'), ('one_time', 'One Time')], default='monthly', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online'), ('cheque', 'Cheque'), ('upi', 'UPI')], max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('delist', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_collections', to='school_management.academicyear')),
                ('class_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_collections', to='school_management.classlist')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_collections', to='company_account.companies')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_collections', to='school_management.classfeestructure')),
                ('student_academic_rcord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_collections', to='school_management.studentacademicrecord')),
            ],
            options={
                'unique_together': {('student_academic_rcord', 'academic_year', 'installment_name')},
            },
        ),
    ]
