# Generated by Django 6.0.3 on 2026-04-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0029_studentfeescollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademicrecord',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('promoted', 'Promoted'), ('detained', 'Detained'), ('passed_out', 'Passed Out'), ('left', 'Left')], default='active', max_length=20),
        ),
    ]
