# Generated by Django 6.0.3 on 2026-04-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0032_remove_studentfeescollection_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeescollection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
