# Generated by Django 6.0.3 on 2026-05-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school_management", "0033_alter_studentfeescollection_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="examschedule",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_schedules",
                to="school_management.academicyear",
            ),
        ),
    ]
