# Generated by Django 6.0.3 on 2026-04-09 13:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_account', '0009_companyuser_teacher_subject_and_class_lists'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_profile', to='company_account.companies')),
            ],
            options={
                'ordering': ['-created_on', '-id'],
            },
        ),
    ]
