# Generated by Django 6.0.3 on 2026-04-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_management', '0003_alter_patient_billing_status'),
        ('company_account', '0009_companyuser_teacher_subject_and_class_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='company_account.companies'),
        ),
    ]
