# Generated by Django 6.0.3 on 2026-03-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorfees',
            options={'ordering': ('doctor__username',)},
        ),
    ]
