# Generated by Django 6.0.3 on 2026-03-13 12:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_account', '0001_initial'),
        ('hospital_management', '0002_alter_doctorfees_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorfees',
            options={'ordering': ('doctor__name',)},
        ),
        migrations.AddField(
            model_name='ipdbooking',
            name='policy_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='administrationtype',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administration_types', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bed', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='department',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='doctorfees',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_fees', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='doctorfees',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_entries', to='company_account.companyuser'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedules', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='company_account.companyuser'),
        ),
        migrations.AlterField(
            model_name='doctortype',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_types', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='dutyroaster',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duty_roasters', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='dutyroaster',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_roasters', to='company_account.companyuser'),
        ),
        migrations.AlterField(
            model_name='emergencyvisit',
            name='attending_doctor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emer_bookings', to='company_account.companyuser'),
        ),
        migrations.AlterField(
            model_name='emergencyvisit',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emer_bookings', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='ipdbilling',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipd_billings', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='ipdbooking',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipd_bookings', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='ipdbooking',
            name='consulting_doctors',
            field=models.ManyToManyField(blank=True, related_name='consulting_ipd_bookings', to='company_account.companyuser'),
        ),
        migrations.AlterField(
            model_name='ipdbooking',
            name='treatment_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_ipd_bookings', to='company_account.companyuser'),
        ),
        migrations.AlterField(
            model_name='ipdpayment',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipd_payments', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='opdticketbooking',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='opdticketbooking',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opd_bookings', to='company_account.companyuser'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opd_bookings', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='ratechart',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_chart', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='room',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='staffdepartment',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_departments', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='staffjobtitle',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_department_job_titles', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward', to='company_account.companies'),
        ),
        migrations.CreateModel(
            name='InsuaranceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=150)),
                ('plan_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('delist', models.BooleanField(default=False)),
                ('delisted_by', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('delisted_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('companies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insuarance_providers', to='company_account.companies')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='ratechart',
            name='insuarance_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_charts', to='hospital_management.insuaranceprovider'),
        ),
        migrations.AlterField(
            model_name='ipdbooking',
            name='insurance_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_bookings', to='hospital_management.insuaranceprovider'),
        ),
    ]
