# Generated by Django 6.0.3 on 2026-03-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='role',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('administration', 'Administration'), ('staff', 'Staff'), ('user', 'User')], default='', max_length=32),
        ),
    ]
