# Generated by Django 6.0.3 on 2026-03-12 11:07

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_organization_name_and_more'),
        ('hospital_management', '0002_alter_doctorfees_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='organization_user',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='organization_user',
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='state',
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='about',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='aliasName',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='app_wise_home_pages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=500, null=True), blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='attachment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='can_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='disclaimer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='excellency_point',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='fatherOrHusband',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='firstLoggedIn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='is_googleuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='is_mobile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='password_reset_link_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='password_reset_token',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='registrationDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='subscription_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='administration_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_users', to='hospital_management.administrationtype'),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='association_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='created_by',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='delisted_by',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='delisted_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_users', to='hospital_management.department'),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='doctor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_users', to='hospital_management.doctortype'),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='email',
            field=models.EmailField(max_length=60, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='medical_council_registration',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='role',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='staff_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='hospital_management.staffdepartment'),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='staff_job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='hospital_management.staffjobtitle'),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='updated_by',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='whatsapp_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='AdministrationProfile',
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
