# Generated by Django 6.0.3 on 2026-03-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_doctorprofile_organization_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='level',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
