# Generated by Django 6.0.3 on 2026-03-13 09:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_organizationinfo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinfo',
            name='address',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='admin_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='branch_offices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=None, null=True), blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='city',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='comments',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='country',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='currency_code',
            field=models.CharField(default='USD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='date_format',
            field=models.CharField(default='MMM DD, YYYY', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='email',
            field=models.EmailField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='head_office',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='head_office_gstin',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='head_office_state',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='language',
            field=models.CharField(default='en-US', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='mobile_for_crm',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='mobile_no',
            field=models.CharField(default='9999999999', max_length=15),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='organization_logo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='organization_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='pin',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='whatsapp_for_crm',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizationinfo',
            name='crm_gmail_password',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizationinfo',
            name='gmail_for_crm',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
