# Generated by Django 6.0.3 on 2026-03-13 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organizationinfo_address_organizationinfo_admin_name_and_more'),
        ('hospital_management', '0002_alter_doctorfees_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationuser',
            name='administration_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_doctor_users', to='hospital_management.administrationtype'),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_doctor_users', to='hospital_management.department'),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='doctor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_doctor_users', to='hospital_management.doctortype'),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='staff_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_staff_users', to='hospital_management.staffdepartment'),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='staff_job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_staff_users', to='hospital_management.staffjobtitle'),
        ),
    ]
