# Generated by Django 6.0.3 on 2026-03-16 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_organizationuser_administration_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='active_from',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='active_upto',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='registrationDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
