# Generated by Django 6.0.3 on 2026-03-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_organization_active_from_organization_active_upto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
