# Generated by Django 6.0.3 on 2026-03-17 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='code',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='phone',
        ),
    ]
