# Generated by Django 6.0.3 on 2026-03-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_loginactivity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginactivity',
            new_name='accounts_lo_user_id_99eafe_idx',
            old_name='accounts_lo_user_id_7e6b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='loginactivity',
            new_name='accounts_lo_access__d65cde_idx',
            old_name='accounts_lo_access__0df5fa_idx',
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
