import { Suspense } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Sidebar from "../components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const HEADER_HEIGHT = "74px";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} h-[100dvh] overflow-hidden antialiased`}
        style={{ "--header-height": HEADER_HEIGHT }}
      >
        <Header  />
        <Suspense fallback={null}>
          <Sidebar />
        </Suspense>
        <div className="fixed inset-x-0 top-[var(--header-height)] h-[calc(100dvh-var(--header-height))] overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
