# Generated by Django 6.0.3 on 2026-03-12 09:12

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoSuggestionModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, null=True)),
                ('src', models.CharField(default=None, null=True)),
                ('notes', models.CharField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorMessageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None)),
                ('msg', models.CharField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('type', models.CharField(default=None, max_length=200)),
                ('url', models.CharField(default=None, max_length=200)),
                ('thumbnail', models.BooleanField(default=False)),
                ('uploaded_by', models.CharField(default=None, max_length=200)),
                ('uploaded_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ChartConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=50)),
                ('chart_identity', models.CharField(default=None, max_length=50)),
                ('graph_title', models.CharField(default='', max_length=50)),
                ('graph_type', models.CharField(default=None, max_length=50)),
                ('x_axis', models.CharField(default=None, max_length=50)),
                ('y_axis', models.CharField(default=None, max_length=50, null=True)),
                ('value', models.CharField(default=None, max_length=50)),
                ('group_by', models.CharField(default=None, max_length=50)),
                ('position', models.JSONField(blank=True, default=None, null=True)),
                ('style', models.JSONField(blank=True, default=None, null=True)),
                ('view', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=None, null=True), blank=True, default=list, null=True)),
                ('company', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('address', models.CharField(default=None, max_length=200)),
                ('country', models.CharField(default=None, max_length=50)),
                ('state', models.CharField(default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=50)),
                ('pin', models.IntegerField(default=None)),
                ('note', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('lat', models.CharField(default='0.0', max_length=50, null=True)),
                ('lng', models.CharField(default='0.0', max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_to_company', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='LocationCustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esi_reg_no', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('p_tax_reg_no', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('principal_employer_name_adds', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('work_nature', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_by', models.CharField(default='', max_length=50, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('company', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                # ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_management.customer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.location')),
            ],
        ),
        migrations.CreateModel(
            name='LocationDesignationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('designation_code', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('start_date', models.DateTimeField(blank=True, default='', null=True)),
                ('basic_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('allowance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('incentive', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('gross_monthly_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('ot_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('note', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('salary_type', models.CharField(default='Monthly', max_length=10, null=True)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('company', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.location')),
            ],
        ),
        migrations.CreateModel(
            name='MailFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50, null=True)),
                ('table_id', models.IntegerField(blank=True, null=True)),
                ('first_mail_date', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('frequency_type', models.CharField(default=None, max_length=10)),
                ('repeat_times', models.IntegerField(blank=True, null=True)),
                ('scheduled_dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(blank=True, null=True), blank=True, null=True)),
                ('next_mail_date', models.DateTimeField(blank=True, null=True)),
                ('repeat_counter', models.IntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('company', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('note', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('delist', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.location')),
            ],
        ),
        migrations.CreateModel(
            name='Compartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('note', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('sub_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.sublocation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='company_wise_location_unique'),
        ),
        migrations.AlterUniqueTogether(
            name='locationcustomerinfo',
            unique_together={('company', 'location')},
        ),
        migrations.AddConstraint(
            model_name='locationdesignationrate',
            constraint=models.UniqueConstraint(fields=('company', 'location', 'designation', 'start_date'), name='location_designation_rate'),
        ),
        migrations.AlterUniqueTogether(
            name='mailfrequency',
            unique_together={('company', 'table_name', 'table_id')},
        ),
        migrations.AddConstraint(
            model_name='sublocation',
            constraint=models.UniqueConstraint(fields=('company', 'location', 'name'), name='location_wise_sub_location_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='compartment',
            constraint=models.UniqueConstraint(fields=('company', 'sub_location', 'name'), name='sub_location_wise_compartment_name_unique'),
        ),
    ]
