# Generated by Django 6.0.3 on 2026-04-07 12:07

import django.db.models.deletion
from django.db import migrations, models


def drop_existing_company_fk_constraints(apps, schema_editor):
    connection = schema_editor.connection
    tables = {
        "shared_location",
        "shared_sublocation",
        "shared_compartment",
    }

    with connection.cursor() as cursor:
        for table_name in tables:
            constraints = connection.introspection.get_constraints(cursor, table_name)
            for constraint_name, constraint in constraints.items():
                if constraint.get("foreign_key") and constraint.get("columns") == [
                    "company_id"
                ]:
                    schema_editor.execute(
                        f'ALTER TABLE "{table_name}" DROP CONSTRAINT "{constraint_name}"'
                    )


def remap_shared_company_refs(apps, schema_editor):
    Location = apps.get_model("shared", "Location")
    SubLocation = apps.get_model("shared", "SubLocation")
    Compartment = apps.get_model("shared", "Compartment")
    Companies = apps.get_model("company_account", "Companies")

    def resolve_company_id(old_company_id):
        if not old_company_id:
            return None
        company = Companies.objects.filter(
            organization_id=str(old_company_id)
        ).values_list("id", flat=True).first()
        return company

    for model in (Location, SubLocation, Compartment):
        for row in model.objects.all().iterator():
            new_company_id = resolve_company_id(row.company_id)
            if new_company_id and new_company_id != row.company_id:
                model.objects.filter(pk=row.pk).update(company_id=new_company_id)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('company_account', '0009_companyuser_teacher_subject_and_class_lists'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(drop_existing_company_fk_constraints, noop_reverse),
        migrations.RunPython(remap_shared_company_refs, noop_reverse),
        migrations.AlterField(
            model_name='compartment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='location',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_to_company', to='company_account.companies'),
        ),
        migrations.AlterField(
            model_name='sublocation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_account.companies'),
        ),
    ]
