# Generated by Django 6.0.4 on 2026-05-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_compartment_company_alter_location_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationCustomerInfo',
        ),
    ]
