# Generated by Django 6.0.3 on 2026-03-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='organization_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='organization_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='organization_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
