# Generated by Django 6.0.3 on 2026-03-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_account', '0002_companies_organization_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='main_category',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='sub_category',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
