# Generated by Django 6.0.3 on 2026-03-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_account', '0007_companies_school_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='city',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='experience',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='is_head_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='pin',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='qualification',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='state',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
