# Generated by Django 6.0.3 on 2026-05-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_account', '0010_companies_email_mobile_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='country',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
